How Big is the data?

In [1]:
import pandas as pd
import numpy as np
import gc

In [3]:
df = pd.read_csv(r"datasets\train_merged.csv")

In [5]:
df.shape

(307511, 1076)

How does the data look like ?

In [6]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,PREV_PRODUCT_COMBINATION_Cash X-Sell: low_mean,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle_mean,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.333333,0.0,0.333333,0.0,0.333333,0.0,0.000000,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,1.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.222222,0.0,0.111111,0.0,0.111111,0.0,0.000000,0.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.000000,0.5,0.166667,0.0,0.000000,0.0,0.166667,0.0,0.0,0.0

In [7]:
df.sample(20)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,PREV_PRODUCT_COMBINATION_Cash X-Sell: low_mean,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle_mean,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean
100808,217042,0,Cash loans,F,Y,Y,0,90000.0,112500.0,13482.0,...,0.000000,0.000000,0.000000,0.0,0.5,0.0,0.50,0.0,0.000000,0.0
189972,320270,0,Cash loans,M,Y,Y,0,139500.0,508495.5,24592.5,...,0.000000,0.333333,0.333333,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
37486,143424,0,Cash loans,M,N,N,0,76500.0,225000.0,10620.0,...,0.000000,0.000000,0.000000,0.0,0.5,0.0,0.50,0.0,0.000000,0.0
168177,294944,0,Cash loans,F,N,Y,1,202500.0,679500.0,24201.0,...,0.000000,0.000000,0.400000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
211543,345140,0,Cash loans,F,N,N,0,180000.0,770292.0,30676.5,...,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
71443,182852,0,Cash loans,F,N,N,0,175500.0,547272.0,30690.0,...,0.000000,0.000000,0.500000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
28112,132677,0,Cash loans,F,Y,Y,0,157500.0,447768.0,29151.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.00,0.0,0.142857,0.0
110287,227921,0,Cash loans,M,Y,Y,0,108000.0,247500.0,29502.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243143,381494,0,Cash loans,F,N,Y,0,315000.0,254700.0,14751.0,...,0.400000,0.100000,0.100000,0.0,0.0,0.0,0.30,0.0,0.000000,0.0
112506,230511,0,Cash loans,F,N,Y,0,81000.0,630747.0,25452.0,...,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
300329,447936,0,Cash loans,M,Y,N,1,427500.0,808650.0,31464.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
76292,188469,0,Cash loans,F,N,N,0,225000.0,555273.0,18040.5,...,0.000000,0.000000,0.000000,0.0,0.2,0.2,0.00,0.0,0.000000,0.0
134732,256271,1,Cash loans,F,N,Y,0,99000.0,808650.0,26217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7369,108589,0,Cash loans,M,N,Y,0,180000.0,309420.0,14553.0,...,0.444444,0.000000,0.111111,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
133570,254913,1,Cash loans,F,N,N,0,90000.0,469152.0,25578.0,...,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
147151,270611,0,Cash loans,F,N,Y,0,202500.0,1032093.0,46039.5,...,0.000000,0.100000,0.100000,0.0,0.0,0.0,0.10,0.0,0.000000,0.0
52666,160995,0,Cash loans,F,N,Y,0,49500.0,123637.5,8302.5,...,0.250000,0.250000,0.000000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0
183889,313140,0,Cash loans,F,N,Y,0,112500.0,746626.5,31518.0,...,0.250000,0.000000,0.375000,0.0,0.0,0.0,0.25,0.0,0.000000,0.0
292191,438491,0,Revolving loans,F,Y,Y,2,67500.0,180000.0,9000.0,...,0.000000,0.200000,0.000000,0.0,0.2,0.0,0.40,0.2,0.000000,0.0
232068,368802,0,Cash loans,M,Y,Y,1,112500.0,288000.0,30370.5,...,0.000000,0.000000,0.400000,0.0,0.2,0.0,0.40,0.0,0.000000,0.0

In [8]:
df.tail()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,PREV_PRODUCT_COMBINATION_Cash X-Sell: low_mean,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle_mean,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0.000,0.00,0.0,0.0,0.000,0.0,1.00,0.0,0.0,0.0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0.000,0.00,0.0,1.0,0.000,0.0,0.00,0.0,0.0,0.0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0.000,0.00,0.0,0.0,0.000,0.0,1.00,0.0,0.0,0.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0.000,0.00,0.5,0.0,0.000,0.0,0.50,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0.125,0.25,0.0,0.0,0.125,0.0,0.25,0.0,0.0,0.0

What is the datatype of the collumns ?

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 1076 entries, SK_ID_CURR to PREV_PRODUCT_COMBINATION_POS others without interest_mean
dtypes: float64(1019), int64(41), object(16)
memory usage: 2.5+ GB

Are there any missing values ?

In [13]:
df.isnull().sum()

SK_ID_CURR                                                         0
TARGET                                                             0
NAME_CONTRACT_TYPE                                                 0
CODE_GENDER                                                        0
FLAG_OWN_CAR                                                       0
                                                               ...
PREV_PRODUCT_COMBINATION_POS industry without interest_mean    16454
PREV_PRODUCT_COMBINATION_POS mobile with interest_mean         16454
PREV_PRODUCT_COMBINATION_POS mobile without interest_mean      16454
PREV_PRODUCT_COMBINATION_POS other with interest_mean          16454
PREV_PRODUCT_COMBINATION_POS others without interest_mean      16454
Length: 1076, dtype: int64

How does the data look mathematically ?

In [14]:
df.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,PREV_PRODUCT_COMBINATION_Cash X-Sell: low_mean,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle_mean,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,...,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000,291057.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,...,0.053143,0.062561,0.206873,0.066197,0.086606,0.011408,0.168719,0.021147,0.021192,0.002428
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,...,0.117884,0.133861,0.293269,0.180934,0.215807,0.081320,0.273860,0.109113,0.112013,0.038717
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,...,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Are there any duplicate values ?

In [15]:
df.duplicated().sum()

0

How is the correlation between cols ?

In [ ]:
df.select_dtypes(include = ['number']).corr()